[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install -y perl make"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install -y perl make"
]

[build.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_NO_VENDOR",
    "OPENSSL_DIR",
    "DEP_OPENSSL_VENDORED"
]