[target.aarch64-unknown-linux-gnu]
image = "ubuntu:24.04"
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libssl-dev:arm64"
]