[package]
name = "satoshi-suite-utxo-selection"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bitcoin.workspace = true
bitcoincore-rpc.workspace = true
serde_json.workspace = true
