[package]
name = "satoshi-suite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Tools for interacting with satoshis"

[dependencies]
satoshi-suite-client.workspace = true
satoshi-suite-config.workspace = true
satoshi-suite-ordinals.workspace = true
satoshi-suite-utxo-selection.workspace = true
satoshi-suite-signing.workspace = true
satoshi-suite-wallet.workspace = true

bitcoin.workspace = true
bitcoincore-rpc.workspace = true
clap.workspace = true
env_logger.workspace = true
hex.workspace = true
ordinals.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "satoshi-suite"
path = "src/main.rs"