name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}
      
      - name: Package Binary
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../satoshi-suite-${{ github.ref_name }}-${{ matrix.target }}.tar.gz satoshi-suite
          cd ../../..

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: satoshi-suite-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: binaries
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: satoshi-suite-*
          generate_release_notes: true